create table public.tracking (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title character varying null,
  month smallint null,
  tracking json null,
  constraint tracking_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO "public"."tracking" ("id", "created_at", "title", "month", "tracking") 
VALUES (1, '2026-07-23 17:12:12+00', 'Đọc sách', 7, '[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]');

create table public.weekly (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  week smallint null,
  "isCurrWeek" boolean null,
  "dayOfWeek" smallint null,
  title character varying null,
  "isDone" boolean null,
  constraint weekly_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO "public"."weekly" ("id", "created_at", "week", "isCurrWeek", "dayOfWeek", "title", "isDone") 
VALUES (1, '2026-07-24 11:06:31.49401+00', 3, false, 0, '[P.Ngủ] Dọn dẹp các vật dụng', true), 
      (2, '2026-07-24 11:07:23.499552+00', 4, true, 4, '[Lầu 1] Quét + lau', true), 
      (3, '2026-07-24 11:08:22.434611+00', 4, true, 4, '[Lầu 2] Quét + lau', true), 
      (4, '2026-07-24 11:08:48.826202+00', 4, true, 5, '[X]Giặt Pad chuột', false);