create table public.todo_list (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  month smallint null default '1'::smallint,
  letter character varying null,
  title character varying null,
  "isDone" boolean null default false,
  "isLeft" boolean null,
  "isFollowing" boolean null default false,
  constraint todo_list_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO "public"."todo_list" ("id", "created_at", "month", "letter", "title", "isDone", "isLeft", "isFollowing") 
VALUES (1, '2026-07-24 14:08:59.482092+00', 7, 'G1', 'Hoàn thành todo web', false, true, true), 
      (2, '2026-07-24 14:09:37.553145+00', 7, 'G2', 'Duy trì dọn dẹp', false, true, true), 
      (3, '2026-07-24 14:10:25.142324+00', 7, 'G3', 'Xác định con đường mới', false, true, false), 
      (4, '2026-07-24 14:11:18.72129+00', 7, 'M1', 'Dọn dẹp bếp', false, false, true), 
      (5, '2026-07-24 14:12:04.669189+00', 7, 'M2', 'Lau nhà', false, false, false);

create table public.tracking (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title character varying null,
  month smallint null,
  tracking json null,
  "startFollowing" smallint null default '0'::smallint,
  "qtyFollowing" smallint null default '0'::smallint,
  constraint tracking_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO "public"."tracking" ("id", "created_at", "title", "month", "tracking") 
VALUES (1, '2026-07-23 17:12:12+00', 'Đọc sách', 7, '[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]');

create table public.weekly (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  week smallint null,
  "isCurrWeek" boolean null,
  "dayOfWeek" smallint null,
  title character varying null,
  "isDone" boolean null,
  month smallint null,
  constraint weekly_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO "public"."weekly" ("id", "created_at", "week", "isCurrWeek", "dayOfWeek", "title", "isDone", "month") 
VALUES (1, '2026-07-24 11:06:31.49401+00', 3, false, 0, '[P.Ngủ] Dọn dẹp các vật dụng', true, 7), 
      (2, '2026-07-24 11:07:23.499552+00', 4, true, 4, '[Lầu 1] Quét + lau', true, 7), 
      (3, '2026-07-24 11:08:22.434611+00', 4, true, 4, '[Lầu 2] Quét + lau', true, 7), 
      (4, '2026-07-24 11:08:48.826202+00', 4, true, 5, '[X]Giặt Pad chuột', false, 7);